# Generated by Django 5.2.4 on 2025-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(choices=[('student', 'Student'), ('labor', 'Labor'), ('job_holder', 'Job Holder'), ('freelancer', 'Freelancer'), ('unemployed', 'Unemployed'), ('other', 'Other')], default='student', max_length=20),
        ),
    ]
